//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord.Addons.Interactive.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discord.Addons.Interactive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◀.
        /// </summary>
        internal static string EmoteBack {
            get {
                return ResourceManager.GetString("EmoteBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏮.
        /// </summary>
        internal static string EmoteFirst {
            get {
                return ResourceManager.GetString("EmoteFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ.
        /// </summary>
        internal static string EmoteInfo {
            get {
                return ResourceManager.GetString("EmoteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔢.
        /// </summary>
        internal static string EmoteJump {
            get {
                return ResourceManager.GetString("EmoteJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏭.
        /// </summary>
        internal static string EmoteLast {
            get {
                return ResourceManager.GetString("EmoteLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶.
        /// </summary>
        internal static string EmoteNext {
            get {
                return ResourceManager.GetString("EmoteNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹.
        /// </summary>
        internal static string EmoteStop {
            get {
                return ResourceManager.GetString("EmoteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0}/{1}.
        /// </summary>
        internal static string PaginatedOptionsFooterFormat {
            get {
                return ResourceManager.GetString("PaginatedOptionsFooterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a paginator. React with the respective icons to change page..
        /// </summary>
        internal static string PaginatedOptionsInformationText {
            get {
                return ResourceManager.GetString("PaginatedOptionsInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline reaction must have message data..
        /// </summary>
        internal static string ReactionCallbackDataException {
            get {
                return ResourceManager.GetString("ReactionCallbackDataException", resourceCulture);
            }
        }
    }
}
