// <auto-generated />
using System;
using Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(FailsafeContext))]
    [Migration("20190729064711_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Core.Models.Destiny2.ActiveMilestone", b =>
                {
                    b.Property<ulong>("MessageId");

                    b.Property<DateTime>("DateExpire");

                    b.Property<string>("GuildName")
                        .IsRequired();

                    b.Property<string>("Memo")
                        .HasMaxLength(1000);

                    b.Property<int>("MilestoneId");

                    b.Property<ulong>("User1");

                    b.Property<ulong>("User2");

                    b.Property<ulong>("User3");

                    b.Property<ulong>("User4");

                    b.Property<ulong>("User5");

                    b.Property<ulong>("User6");

                    b.HasKey("MessageId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("ActiveMilestones");
                });

            modelBuilder.Entity("Core.Models.Destiny2.Catalyst", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("DropLocation")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Masterwork")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Catalysts");
                });

            modelBuilder.Entity("Core.Models.Destiny2.Clan", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("About");

                    b.Property<DateTimeOffset>("CreateDate");

                    b.Property<long>("MemberCount");

                    b.Property<string>("Motto");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Clans");
                });

            modelBuilder.Entity("Core.Models.Destiny2.Clan_Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BungieMembershipId");

                    b.Property<long?>("BungieMembershipType");

                    b.Property<long>("ClanId");

                    b.Property<DateTimeOffset?>("ClanJoinDate");

                    b.Property<DateTimeOffset?>("DateLastPlayed");

                    b.Property<string>("DestinyMembershipId");

                    b.Property<long>("DestinyMembershipType");

                    b.Property<string>("IconPath");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.ToTable("Clan_Members");
                });

            modelBuilder.Entity("Core.Models.Destiny2.Gear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("DropLocation")
                        .HasMaxLength(300);

                    b.Property<string>("IconUrl")
                        .HasMaxLength(1000);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Perk")
                        .HasMaxLength(100);

                    b.Property<string>("PerkDescription")
                        .HasMaxLength(1024);

                    b.Property<string>("SecondPerk")
                        .HasMaxLength(100);

                    b.Property<string>("SecondPerkDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("Type")
                        .HasMaxLength(100);

                    b.Property<bool>("isHaveCatalyst");

                    b.Property<bool>("isWeapon");

                    b.HasKey("Id");

                    b.ToTable("Gears");
                });

            modelBuilder.Entity("Core.Models.Destiny2.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias")
                        .HasMaxLength(50);

                    b.Property<string>("Icon")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("PreviewDesc")
                        .HasMaxLength(1024);

                    b.Property<string>("Type")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Core.Models.Discord.Guild", b =>
                {
                    b.Property<ulong>("Id");

                    b.Property<ulong>("AutoroleID");

                    b.Property<string>("CommandPrefix");

                    b.Property<bool>("EnableLogging");

                    b.Property<bool>("EnableNotification");

                    b.Property<string>("LeaveMessage");

                    b.Property<ulong>("LoggingChannel");

                    b.Property<ulong>("NotificationChannel");

                    b.Property<string>("WelcomeMessage");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Core.Models.Destiny2.ActiveMilestone", b =>
                {
                    b.HasOne("Core.Models.Destiny2.Milestone", "Milestone")
                        .WithMany("ActiveMilestones")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Destiny2.Clan_Member", b =>
                {
                    b.HasOne("Core.Models.Destiny2.Clan", "Clan")
                        .WithMany("Members")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
