//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, for access to unlock participants I do not have the right **Ban members**.
        ///I advise you to enable the right, and after I inform about the completion of work, turn off this right just in case..
        /// </summary>
        internal static string BanPermission {
            get {
                return ResourceManager.GetString("BanPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beep....
        /// </summary>
        internal static string Bip {
            get {
                return ResourceManager.GetString("Bip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple command to test my health..
        /// </summary>
        internal static string BipCommSummary {
            get {
                return ResourceManager.GetString("BipCommSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalyst bonus.
        /// </summary>
        internal static string CatEmbBnsFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbBnsFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get a catalyst.
        /// </summary>
        internal static string CatEmbDrpFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbDrpFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalyst masterwork.
        /// </summary>
        internal static string CatEmbQueFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbQueFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about catalyst for weapon {0}.
        /// </summary>
        internal static string CatEmbTitle {
            get {
                return ResourceManager.GetString("CatEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, {0} is what I know about this catalyst..
        /// </summary>
        internal static string CatFound {
            get {
                return ResourceManager.GetString("CatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: Please enter the full or partial name of the exotic weapon..
        /// </summary>
        internal static string CatInputIsNull {
            get {
                return ResourceManager.GetString("CatInputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Channel created.
        /// </summary>
        internal static string ChanCreEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanCreEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Channel deleted.
        /// </summary>
        internal static string ChanDelEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanDelEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: **{0}**
        ///NSFW **{1}**
        ///Category: {2}.
        /// </summary>
        internal static string ChanEmbFieldDesc {
            get {
                return ResourceManager.GetString("ChanEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this command in {0} seconds..
        /// </summary>
        internal static string CooldownMessage {
            get {
                return ResourceManager.GetString("CooldownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By: {0}.
        /// </summary>
        internal static string DiEvnEmbFooter {
            get {
                return ResourceManager.GetString("DiEvnEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message will be automatically deleted after one minute..
        /// </summary>
        internal static string EmbFooterAboutDel {
            get {
                return ResourceManager.GetString("EmbFooterAboutDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find any inaccuracies, please inform my creator: Cyber_Garret#5898.
        /// </summary>
        internal static string EmbFooterAboutMyMistake {
            get {
                return ResourceManager.GetString("EmbFooterAboutMyMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string ErrorHndlCom {
            get {
                return ResourceManager.GetString("ErrorHndlCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Missing**.
        /// </summary>
        internal static string ExoEmbCatFieldDescNo {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldDescNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **There is**.
        /// </summary>
        internal static string ExoEmbCatFieldDescYes {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldDescYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalyst.
        /// </summary>
        internal static string ExoEmbCatFieldTitle {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to obtain:.
        /// </summary>
        internal static string ExoEmbHowFieldTitle {
            get {
                return ResourceManager.GetString("ExoEmbHowFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, {0} this is what I know about this equipment..
        /// </summary>
        internal static string ExoFound {
            get {
                return ResourceManager.GetString("ExoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: Please enter the full or partial name of the exotic equipment..
        /// </summary>
        internal static string ExoInputIsNull {
            get {
                return ResourceManager.GetString("ExoInputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Total channels: **{0}**
        ///- Guardians on the server: **{1}**
        ///- I send alerts about Xur to **&lt;#{2}&gt;**
        ///- Server logs I write in **&lt;#{3}&gt;**
        ///- I send notifications of new guardians to **&lt;#{4}&gt;**
        ///- When collecting fees for activity, I will mention: **{5}**
        ///- My locale: **{6}**
        ///- Server timezone: **{7}**.
        /// </summary>
        internal static string GuCoEmbDescField {
            get {
                return ResourceManager.GetString("GuCoEmbDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My settings on this server..
        /// </summary>
        internal static string GuCoEmbTitle {
            get {
                return ResourceManager.GetString("GuCoEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information:.
        /// </summary>
        internal static string GuCoEmbTitleField {
            get {
                return ResourceManager.GetString("GuCoEmbTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorole functionality is disabled..
        /// </summary>
        internal static string GuildAutoroleOff {
            get {
                return ResourceManager.GetString("GuildAutoroleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role **{0}** has been saved, now I will automatically issue it to everyone who arrives at the server..
        /// </summary>
        internal static string GuildAutoroleOn {
            get {
                return ResourceManager.GetString("GuildAutoroleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I turned off alerts about changes on the server..
        /// </summary>
        internal static string GuildLogsOff {
            get {
                return ResourceManager.GetString("GuildLogsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now most of the changes on the server, if of course I have rights, I will notify the channel {0}.
        /// </summary>
        internal static string GuildLogsOn {
            get {
                return ResourceManager.GetString("GuildLogsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, now in the messages when collecting for activity I will mention: {0}.
        /// </summary>
        internal static string GuildMilMention {
            get {
                return ResourceManager.GetString("GuildMilMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **No mention**.
        /// </summary>
        internal static string GuildNoMention {
            get {
                return ResourceManager.GetString("GuildNoMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix `{0}` is set for commands.
        /// </summary>
        internal static string GuildPrefixCustom {
            get {
                return ResourceManager.GetString("GuildPrefixCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For commands, the default prefix `!`.
        /// </summary>
        internal static string GuildPrefixDefault {
            get {
                return ResourceManager.GetString("GuildPrefixDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: | At the moment I am not sending any message to new arrivals..
        /// </summary>
        internal static string GuildPrivateWelcomeIsNull {
            get {
                return ResourceManager.GetString("GuildPrivateWelcomeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The welcome message has been deleted successfully..
        /// </summary>
        internal static string GuildPrivateWelcomeRemove {
            get {
                return ResourceManager.GetString("GuildPrivateWelcomeRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : smiley: Welcome message saved..
        /// </summary>
        internal static string GuildPrivateWelcomeSave {
            get {
                return ResourceManager.GetString("GuildPrivateWelcomeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I turned off colorful alerts about new members on the server..
        /// </summary>
        internal static string GuildWelcomeOff {
            get {
                return ResourceManager.GetString("GuildWelcomeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now I will notify about new members in the channel {0}.
        /// </summary>
        internal static string GuildWelcomeOn {
            get {
                return ResourceManager.GetString("GuildWelcomeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I turned off the Xur alerts..
        /// </summary>
        internal static string GuildXurOff {
            get {
                return ResourceManager.GetString("GuildXurOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now I will send news about Xur to the channel {0}.
        /// </summary>
        internal static string GuildXurOn {
            get {
                return ResourceManager.GetString("GuildXurOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string GuMemAddRole {
            get {
                return ResourceManager.GetString("GuMemAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string GuMemRemRole {
            get {
                return ResourceManager.GetString("GuMemRemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: **{0}**
        ///{1} role: **{2}**.
        /// </summary>
        internal static string GuMemRolEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔑 Updated guard role:.
        /// </summary>
        internal static string GuMemRolEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Name:
        ///**{0}**
        ///New name:
        ///**{1}**.
        /// </summary>
        internal static string GuMemUpdEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 Guardian name changed:.
        /// </summary>
        internal static string GuMemUpdEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian {0} has landed, which means that:.
        /// </summary>
        internal static string Hellotxt {
            get {
                return ResourceManager.GetString("Hellotxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin commands.
        /// </summary>
        internal static string HelpEmbAdmFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbAdmFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My main goal is to help the Guardians to gather battle groups, to inform in a timely manner when the messenger of nine Xur arrives or leaves.
        ///I can also provide information on exotic gear, catalysts, and much more.
        ///You can find more information in the documentation section on my [site]({0}).
        /// </summary>
        internal static string HelpEmbDesc {
            get {
                return ResourceManager.GetString("HelpEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main commands.
        /// </summary>
        internal static string HelpEmbMainFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbMainFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity commands.
        /// </summary>
        internal static string HelpEmbMilFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbMilFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoroles Commands.
        /// </summary>
        internal static string HelpEmbSRolFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbSRolFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good day. My name is Neuromatrix, I’m Black Exodus AI adapted for Discord. Successfully functioning with {0}.
        /// </summary>
        internal static string HelpEmbTitle {
            get {
                return ResourceManager.GetString("HelpEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed default locale to: {0}.
        /// </summary>
        internal static string LocaleChanged {
            get {
                return ResourceManager.GetString("LocaleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. I sent out a message to everyone who has the role **{0}**.
        ///- Total Recipients: **{1}**
        ///- Successfully delivered: **{2}**
        ///- Failed to send: **{3}**.
        /// </summary>
        internal static string MailDone {
            get {
                return ResourceManager.GetString("MailDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard, keep in mind that I have no relation to the contents of this message..
        /// </summary>
        internal static string MailEmbFooterDesc {
            get {
                return ResourceManager.GetString("MailEmbFooterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : mailbox_with_mail: You got a message from {0} from the server ** `{1}` **.
        /// </summary>
        internal static string MailEmbTitle {
            get {
                return ResourceManager.GetString("MailEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am starting to send out messages. To all guards with the role **{0}**.
        /// </summary>
        internal static string MailStart {
            get {
                return ResourceManager.GetString("MailStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m preparing the collection of the battle group..
        /// </summary>
        internal static string MilBake {
            get {
                return ResourceManager.GetString("MilBake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity canceled.
        ///{0}.
        /// </summary>
        internal static string MilCanceled {
            get {
                return ResourceManager.GetString("MilCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leadership rights were transferred to another guard. {0}.
        /// </summary>
        internal static string MilChangeLeader {
            get {
                return ResourceManager.GetString("MilChangeLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Note from the leader:** {0}.
        /// </summary>
        internal static string MilEmbDesc {
            get {
                return ResourceManager.GetString("MilEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled due to: {0}.
        /// </summary>
        internal static string MilEmbDescCanceled {
            get {
                return ResourceManager.GetString("MilEmbDescCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Leader of the battle group: **# 1 {0} - {1}**
        ///- To  your place, click on the reaction {2}.
        /// </summary>
        internal static string MilEmbInfDescField {
            get {
                return ResourceManager.GetString("MilEmbInfDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MilEmbInfTitleField {
            get {
                return ResourceManager.GetString("MilEmbInfTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed up in a battle group.
        /// </summary>
        internal static string MilEmbMemTitleField {
            get {
                return ResourceManager.GetString("MilEmbMemTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [By clicking here you will be transferred to the activity in which the time was updated.] ({0}).
        /// </summary>
        internal static string MilEmbTimeFieldDesc {
            get {
                return ResourceManager.GetString("MilEmbTimeFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to milestone.
        /// </summary>
        internal static string MilEmbTimeFieldTitle {
            get {
                return ResourceManager.GetString("MilEmbTimeFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, in {1}. {2}: {3}.
        /// </summary>
        internal static string MilEmbTitle {
            get {
                return ResourceManager.GetString("MilEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings, I want to inform you that the activity leader has changed the start time of the event..
        /// </summary>
        internal static string MilEmbTitleChangeTime {
            get {
                return ResourceManager.GetString("MilEmbTitleChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard, a critical error has occurred. Try again in a couple of minutes, if the error is again write to my creator - Cyber_Garret#5898
        ///Error: {0}.
        /// </summary>
        internal static string MilError {
            get {
                return ResourceManager.GetString("MilError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available activities {0}..
        /// </summary>
        internal static string MilInfEmbTitle {
            get {
                return ResourceManager.GetString("MilInfEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard, you cannot cancel an activity without specifying a reason..
        /// </summary>
        internal static string MilNoReason {
            get {
                return ResourceManager.GetString("MilNoReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity note changed. {0}.
        /// </summary>
        internal static string MilNoteEdited {
            get {
                return ResourceManager.GetString("MilNoteEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I did not understand what activity you want to assemble a battle group..
        /// </summary>
        internal static string MilNotFound {
            get {
                return ResourceManager.GetString("MilNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard, you cannot complete this action, since it is available only to the activity leader..
        /// </summary>
        internal static string MilNotLeader {
            get {
                return ResourceManager.GetString("MilNotLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gathered in the past? You are waiting for the fascinating show &quot;stay alive&quot; performed by my team of the Golden Age. Don&apos;t forget popcorn
        ///Beep ... Good luck and say hello to my captain..
        /// </summary>
        internal static string MilPastTime {
            get {
                return ResourceManager.GetString("MilPastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}. Server: {2}.
        /// </summary>
        internal static string MilRemEmbFooter {
            get {
                return ResourceManager.GetString("MilRemEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to remind you that you will start **{0}** in 15 minutes..
        /// </summary>
        internal static string MilRemEmbTitle {
            get {
                return ResourceManager.GetString("MilRemEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Reserved by the leader**.
        /// </summary>
        internal static string MilReserved {
            get {
                return ResourceManager.GetString("MilReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reserve {0}.
        /// </summary>
        internal static string MilReservedFail {
            get {
                return ResourceManager.GetString("MilReservedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved: {0}
        ///{1}.
        /// </summary>
        internal static string MilReservedOk {
            get {
                return ResourceManager.GetString("MilReservedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity time changed. {0}.
        /// </summary>
        internal static string MilTimeChanged {
            get {
                return ResourceManager.GetString("MilTimeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard, you indicated an unknown time format for me..
        /// </summary>
        internal static string MilTimeError {
            get {
                return ResourceManager.GetString("MilTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor mods 2.0.
        /// </summary>
        internal static string ModEmbTitle {
            get {
                return ResourceManager.GetString("ModEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse rifles, machine guns, shotguns, swords, bows..
        /// </summary>
        internal static string ModFieldArcDesc {
            get {
                return ResourceManager.GetString("ModFieldArcDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        internal static string ModFieldArcTitle {
            get {
                return ResourceManager.GetString("ModFieldArcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve ammunition, persistent sight..
        /// </summary>
        internal static string ModFieldChestDesc {
            get {
                return ResourceManager.GetString("ModFieldChestDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest Armor.
        /// </summary>
        internal static string ModFieldChestTitle {
            get {
                return ResourceManager.GetString("ModFieldChestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing technique, restoration of abilities..
        /// </summary>
        internal static string ModFieldClassItemDesc {
            get {
                return ResourceManager.GetString("ModFieldClassItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Item.
        /// </summary>
        internal static string ModFieldClassItemTitle {
            get {
                return ResourceManager.GetString("ModFieldClassItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of energy to which the type of weapon is attached:.
        /// </summary>
        internal static string ModFieldElementTitle {
            get {
                return ResourceManager.GetString("ModFieldElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload speed, rollback of grenades and melee..
        /// </summary>
        internal static string ModFieldGauntletsDesc {
            get {
                return ResourceManager.GetString("ModFieldGauntletsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauntlets.
        /// </summary>
        internal static string ModFieldGauntletsTitle {
            get {
                return ResourceManager.GetString("ModFieldGauntletsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting, ammunition locators..
        /// </summary>
        internal static string ModFieldHelmetDesc {
            get {
                return ResourceManager.GetString("ModFieldHelmetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmet.
        /// </summary>
        internal static string ModFieldHelmetTitle {
            get {
                return ResourceManager.GetString("ModFieldHelmetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo collector, weapon lightness..
        /// </summary>
        internal static string ModFieldLegDesc {
            get {
                return ResourceManager.GetString("ModFieldLegDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg Armor.
        /// </summary>
        internal static string ModFieldLegTitle {
            get {
                return ResourceManager.GetString("ModFieldLegTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket launchers, auto rifles, submachine guns, plasma rifles, linear plasma rifles..
        /// </summary>
        internal static string ModFieldSolarDesc {
            get {
                return ResourceManager.GetString("ModFieldSolarDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar.
        /// </summary>
        internal static string ModFieldSolarTitle {
            get {
                return ResourceManager.GetString("ModFieldSolarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier type in armor:.
        /// </summary>
        internal static string ModFieldTypeTitle {
            get {
                return ResourceManager.GetString("ModFieldTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revolvers, sniper rifles, grenade launchers, scout rifles, pistols..
        /// </summary>
        internal static string ModFieldVoidDesc {
            get {
                return ResourceManager.GetString("ModFieldVoidDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string ModFieldVoidTitle {
            get {
                return ResourceManager.GetString("ModFieldVoidTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where: &lt;#{0}&gt;
        ///Posted by **{1}**.
        /// </summary>
        internal static string MsgDelEmbDesc {
            get {
                return ResourceManager.GetString("MsgDelEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message text:.
        /// </summary>
        internal static string MsgDelEmbFieldTitle {
            get {
                return ResourceManager.GetString("MsgDelEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Message deleted.
        /// </summary>
        internal static string MsgDelEmbTitle {
            get {
                return ResourceManager.GetString("MsgDelEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where: &lt;#{0}&gt;.
        /// </summary>
        internal static string MsgUpdEmbDesc {
            get {
                return ResourceManager.GetString("MsgUpdEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New text:.
        /// </summary>
        internal static string MsgUpdEmbNewFieldTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbNewFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old text:.
        /// </summary>
        internal static string MsgUpdEmbOldFieldTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbOldFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Updated message.
        /// </summary>
        internal static string MsgUpdEmbTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want a custom bot? Write to my creator Cyber_Garret#5898.
        /// </summary>
        internal static string MyAd {
            get {
                return ResourceManager.GetString("MyAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.neira.app/img/neira.png.
        /// </summary>
        internal static string NeiraFooterIcon {
            get {
                return ResourceManager.GetString("NeiraFooterIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://neira.app/.
        /// </summary>
        internal static string NeiraWebSite {
            get {
                return ResourceManager.GetString("NeiraWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightfall.
        /// </summary>
        internal static string Nightfall {
            get {
                return ResourceManager.GetString("Nightfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: This information is not in my database. : frowning:.
        /// </summary>
        internal static string NotFoundInDB {
            get {
                return ResourceManager.GetString("NotFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: | This command is not available in private messages..
        /// </summary>
        internal static string NotInGuildText {
            get {
                return ResourceManager.GetString("NotInGuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : x: | This command is not available in private messages..
        /// </summary>
        internal static string OnlyForGuildOwner {
            get {
                return ResourceManager.GetString("OnlyForGuildOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other activities.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started voting..
        /// </summary>
        internal static string PollEmbAuthorName {
            get {
                return ResourceManager.GetString("PollEmbAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting topic.
        /// </summary>
        internal static string PollEmbTpcFieldTitle {
            get {
                return ResourceManager.GetString("PollEmbTpcFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task completed successfully. Deleted {0} posts. _This message will be automatically deleted ._.
        /// </summary>
        internal static string PurgeDone {
            get {
                return ResourceManager.GetString("PurgeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin cleaning the channel..
        /// </summary>
        internal static string PurgeStart {
            get {
                return ResourceManager.GetString("PurgeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid.
        /// </summary>
        internal static string Raid {
            get {
                return ResourceManager.GetString("Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, Vex pseudo-random number generator displayed:.
        /// </summary>
        internal static string RndEmbFieldTitle {
            get {
                return ResourceManager.GetString("RndEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify a Role or indicated less than 1 or more than 10 random ones..
        /// </summary>
        internal static string RndErrorStart {
            get {
                return ResourceManager.GetString("RndErrorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: **{0}**
        ///Color: **{1}**.
        /// </summary>
        internal static string RolDelEmbDesc {
            get {
                return ResourceManager.GetString("RolDelEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Role removed.
        /// </summary>
        internal static string RolDelEmbTitle {
            get {
                return ResourceManager.GetString("RolDelEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, I deleted all recorded roles in my database..
        /// </summary>
        internal static string SlfRolClear {
            get {
                return ResourceManager.GetString("SlfRolClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on {0} to get the role {1}.
        /// </summary>
        internal static string SlfRolEmbDescField {
            get {
                return ResourceManager.GetString("SlfRolEmbDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, not a single autorole is recorded in my database..
        /// </summary>
        internal static string SlfRolEmpty {
            get {
                return ResourceManager.GetString("SlfRolEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, I could not save the emoji. Are you sure you are using server emoji?.
        /// </summary>
        internal static string SlfRolErrorEmoji {
            get {
                return ResourceManager.GetString("SlfRolErrorEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In my database, the following autoroli and emoji are attached to them:.
        /// </summary>
        internal static string SlfRolList {
            get {
                return ResourceManager.GetString("SlfRolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, you did not indicate the text of the message..
        /// </summary>
        internal static string SlfRolNoText {
            get {
                return ResourceManager.GetString("SlfRolNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captain, the role and\\or emoji that you said is already used in the autorole system..
        /// </summary>
        internal static string SlfRolRoleOrEmojiExist {
            get {
                return ResourceManager.GetString("SlfRolRoleOrEmojiExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, you did not indicate the role and\\or emoji..
        /// </summary>
        internal static string SlfRolRoleOrEmojIsNull {
            get {
                return ResourceManager.GetString("SlfRolRoleOrEmojIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Captain, I saved this bunch of roles {0} and {1} in my database..
        /// </summary>
        internal static string SlfRolSucAdd {
            get {
                return ResourceManager.GetString("SlfRolSucAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done. I went through the list of **{0}** blocked guards.
        ///- Successfully unlocked: **{1}**
        ///- Failed to unlock: **{2}**
        ///*If there are too many unsuccessful attempts, try in a couple of minutes, as Discord can block such massive actions.*.
        /// </summary>
        internal static string UnbanDone {
            get {
                return ResourceManager.GetString("UnbanDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain, I counted {0} guards on the list of blocked ones.
        ///I proceed to mass unlock all the guards..
        /// </summary>
        internal static string UnbanStart {
            get {
                return ResourceManager.GetString("UnbanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔨 Guardian was banned.
        /// </summary>
        internal static string UsrBanEmbTitle {
            get {
                return ResourceManager.GetString("UsrBanEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦶 Guardian was banished.
        /// </summary>
        internal static string UsrKicEmbTitle {
            get {
                return ResourceManager.GetString("UsrKicEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server was known as:
        ///**{0}**
        ///Discord Guardian Name
        ///**{1}**.
        /// </summary>
        internal static string UsrLefEmbDesc {
            get {
                return ResourceManager.GetString("UsrLefEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause:.
        /// </summary>
        internal static string UsrLefEmbFieldTitle {
            get {
                return ResourceManager.GetString("UsrLefEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 Guardian left the server.
        /// </summary>
        internal static string UsrLefEmbTitle {
            get {
                return ResourceManager.GetString("UsrLefEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, on server used {0} timezone..
        /// </summary>
        internal static string UTCChanged {
            get {
                return ResourceManager.GetString("UTCChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect UTC range..
        /// </summary>
        internal static string UTCIncorrect {
            get {
                return ResourceManager.GetString("UTCIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish {0}/{1}.
        /// </summary>
        internal static string WishFooterFormat {
            get {
                return ResourceManager.GetString("WishFooterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the server {0}.
        /// </summary>
        internal static string WlcmEmbTitle {
            get {
                return ResourceManager.GetString("WlcmEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot determine the exact location of Xur.
        ///[Here you can find his position](https://whereisxur.com/)
        ///[Or here](https://ftw.in/game/destiny-2/find-xur).
        /// </summary>
        internal static string XurArriveEmbDesc {
            get {
                return ResourceManager.GetString("XurArriveEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guards! Xur has arrived in the solar system!.
        /// </summary>
        internal static string XurArriveEmbTitle {
            get {
                return ResourceManager.GetString("XurArriveEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He just disappeared! :open_mouth: .
        /// </summary>
        internal static string XurLeaveEmbDesc {
            get {
                return ResourceManager.GetString("XurLeaveEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Xur left the solar system..
        /// </summary>
        internal static string XurLeaveEmbTitle {
            get {
                return ResourceManager.GetString("XurLeaveEmbTitle", resourceCulture);
            }
        }
    }
}
