//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бип....
        /// </summary>
        internal static string Bip {
            get {
                return ResourceManager.GetString("Bip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Простая команда проверки моей работоспособности..
        /// </summary>
        internal static string BipCommSummary {
            get {
                return ResourceManager.GetString("BipCommSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бонус катализатор.
        /// </summary>
        internal static string CatEmbBnsFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbBnsFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как получить катализатор.
        /// </summary>
        internal static string CatEmbDrpFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbDrpFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание катализатора.
        /// </summary>
        internal static string CatEmbQueFieldTitle {
            get {
                return ResourceManager.GetString("CatEmbQueFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о катализаторе для оружия {0}.
        /// </summary>
        internal static string CatEmbTitle {
            get {
                return ResourceManager.GetString("CatEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итак, {0} вот что мне известно про этот катализатор..
        /// </summary>
        internal static string CatFound {
            get {
                return ResourceManager.GetString("CatFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x: Пожалуйста, введите полное или частичное название экзотического оружия..
        /// </summary>
        internal static string CatInputIsNull {
            get {
                return ResourceManager.GetString("CatInputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Создан канал.
        /// </summary>
        internal static string ChanCreEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanCreEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Удален канал.
        /// </summary>
        internal static string ChanDelEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanDelEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: **{0}**\nNSFW **{2}**\nКатегория: {3}.
        /// </summary>
        internal static string ChanEmbFieldDesc {
            get {
                return ResourceManager.GetString("ChanEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты сможешь использовать эту команду через {0} сек..
        /// </summary>
        internal static string CooldownMessage {
            get {
                return ResourceManager.GetString("CooldownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем: {0}.
        /// </summary>
        internal static string DiEvnEmbFooter {
            get {
                return ResourceManager.GetString("DiEvnEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение будет автоматически удалено через одну минуту..
        /// </summary>
        internal static string EmbFooterAboutDel {
            get {
                return ResourceManager.GetString("EmbFooterAboutDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если нашли какие либо неточности, сообщите моему создателю: Cyber_Garret#5898.
        /// </summary>
        internal static string EmbFooterAboutMyMistake {
            get {
                return ResourceManager.GetString("EmbFooterAboutMyMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка:.
        /// </summary>
        internal static string ErrorHndlCom {
            get {
                return ResourceManager.GetString("ErrorHndlCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Отсутствует**.
        /// </summary>
        internal static string ExoEmbCatFieldDescNo {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldDescNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Есть**.
        /// </summary>
        internal static string ExoEmbCatFieldDescYes {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldDescYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катализатор.
        /// </summary>
        internal static string ExoEmbCatFieldTitle {
            get {
                return ResourceManager.GetString("ExoEmbCatFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как получить:.
        /// </summary>
        internal static string ExoEmbHowFieldTitle {
            get {
                return ResourceManager.GetString("ExoEmbHowFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итак, {0} вот что мне известно про это снаряжение..
        /// </summary>
        internal static string ExoFound {
            get {
                return ResourceManager.GetString("ExoFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x: Пожалуйста, введите полное или частичное название экзотического снаряжения..
        /// </summary>
        internal static string ExoInputIsNull {
            get {
                return ResourceManager.GetString("ExoInputIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлена.
        /// </summary>
        internal static string GuMemAddRole {
            get {
                return ResourceManager.GetString("GuMemAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрана.
        /// </summary>
        internal static string GuMemRemRole {
            get {
                return ResourceManager.GetString("GuMemRemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя: **{0}**\n{1} роль: **{2}**.
        /// </summary>
        internal static string GuMemRolEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔑 Обновлена роль стража:.
        /// </summary>
        internal static string GuMemRolEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущее имя:\n**{0}**\nНовое имя:\n**{1}**.
        /// </summary>
        internal static string GuMemUpdEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 Имя стража изменено:.
        /// </summary>
        internal static string GuMemUpdEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страж {0} приземлился, а это значит что:.
        /// </summary>
        internal static string Hellotxt {
            get {
                return ResourceManager.GetString("Hellotxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды администраторов.
        /// </summary>
        internal static string HelpEmbAdmFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbAdmFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя основная цель - помогать Стражам собирать боевые группы, своевременно сообщать, когда прибывает или улетает посланник девяти Зур.\nТакже я могу предоставить информацию о экзотическом снаряжении, катализаторах и много чего еще.\nБольше информации ты можешь найти в разделе документация на моем [сайте]({0}).
        /// </summary>
        internal static string HelpEmbDesc {
            get {
                return ResourceManager.GetString("HelpEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные команды.
        /// </summary>
        internal static string HelpEmbMainFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbMainFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды активностей.
        /// </summary>
        internal static string HelpEmbMilFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbMilFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды настройки Автороли.
        /// </summary>
        internal static string HelpEmbSRolFieldTitle {
            get {
                return ResourceManager.GetString("HelpEmbSRolFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброго времени суток. Меня зовут Нейроматрица, я ИИ &quot;Черного исхода&quot; адаптированный для Discord. Успешно функционирую с {0}.
        /// </summary>
        internal static string HelpEmbTitle {
            get {
                return ResourceManager.GetString("HelpEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \u200b.
        /// </summary>
        internal static string InvisibleString {
            get {
                return ResourceManager.GetString("InvisibleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Заметка от лидера:** {0}.
        /// </summary>
        internal static string MilEmbDesc {
            get {
                return ResourceManager.GetString("MilEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Лидер боевой группы: **#1 {0} - {1}**\n- Чтобы за вами закрепилось место нажмите на реакцию {2}.
        /// </summary>
        internal static string MilEmbInfDescField {
            get {
                return ResourceManager.GetString("MilEmbInfDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string MilEmbInfTitleField {
            get {
                return ResourceManager.GetString("MilEmbInfTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В боевую группу записались.
        /// </summary>
        internal static string MilEmbMemTitleField {
            get {
                return ResourceManager.GetString("MilEmbMemTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, в {1} по {2}. {3}: {4}.
        /// </summary>
        internal static string MilEmbTitle {
            get {
                return ResourceManager.GetString("MilEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные активности {0}..
        /// </summary>
        internal static string MilInfEmbTitle {
            get {
                return ResourceManager.GetString("MilInfEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}. Сервер: {2}.
        /// </summary>
        internal static string MilRemEmbFooter {
            get {
                return ResourceManager.GetString("MilRemEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу вам напомнить, что у вас через 15 минут начнется **{0}**..
        /// </summary>
        internal static string MilRemEmbTitle {
            get {
                return ResourceManager.GetString("MilRemEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где: &lt;#{0}&gt;\nАвтор сообщения: **{1}**.
        /// </summary>
        internal static string MsgDelEmbDesc {
            get {
                return ResourceManager.GetString("MsgDelEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🗑 Удалено сообщение.
        /// </summary>
        internal static string MsgDelEmbTitle {
            get {
                return ResourceManager.GetString("MsgDelEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где: &lt;#{0}&gt;.
        /// </summary>
        internal static string MsgUpdEmbDesc {
            get {
                return ResourceManager.GetString("MsgUpdEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый текст:.
        /// </summary>
        internal static string MsgUpdEmbNewFieldTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbNewFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий текст:.
        /// </summary>
        internal static string MsgUpdEmbOldFieldTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbOldFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📝 Обновлено сообщение.
        /// </summary>
        internal static string MsgUpdEmbTitle {
            get {
                return ResourceManager.GetString("MsgUpdEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумрачный налет.
        /// </summary>
        internal static string Nightfall {
            get {
                return ResourceManager.GetString("Nightfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x: Этой информации в моей базе данных нет. :frowning:.
        /// </summary>
        internal static string NotFoundInDB {
            get {
                return ResourceManager.GetString("NotFoundInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :x: | Эта команда не доступна в личных сообщениях..
        /// </summary>
        internal static string NotInGuildText {
            get {
                return ResourceManager.GetString("NotInGuildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочие активноcти.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} начал голосование..
        /// </summary>
        internal static string PollEmbAuthorName {
            get {
                return ResourceManager.GetString("PollEmbAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема голосования.
        /// </summary>
        internal static string PollEmbTpcFieldTitle {
            get {
                return ResourceManager.GetString("PollEmbTpcFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейд.
        /// </summary>
        internal static string Raid {
            get {
                return ResourceManager.GetString("Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: **{0}**\nЦвет: **{1}**.
        /// </summary>
        internal static string RolDelEmbDesc {
            get {
                return ResourceManager.GetString("RolDelEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Удалена роль.
        /// </summary>
        internal static string RolDelEmbTitle {
            get {
                return ResourceManager.GetString("RolDelEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔨 Страж был забанен.
        /// </summary>
        internal static string UsrBanEmbTitle {
            get {
                return ResourceManager.GetString("UsrBanEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦶 Страж был выгнан.
        /// </summary>
        internal static string UsrKicEmbTitle {
            get {
                return ResourceManager.GetString("UsrKicEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На сервере был известен как:\n**{0}**\nDiscord имя стража\n**{1}**.
        /// </summary>
        internal static string UsrLefEmbDesc {
            get {
                return ResourceManager.GetString("UsrLefEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина:.
        /// </summary>
        internal static string UsrLefEmbFieldTitle {
            get {
                return ResourceManager.GetString("UsrLefEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 Страж покинул сервер.
        /// </summary>
        internal static string UsrLefEmbTitle {
            get {
                return ResourceManager.GetString("UsrLefEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://neira.su/.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
