//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📖 Создан канал.
        /// </summary>
        internal static string ChanCreEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanCreEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ Удален канал.
        /// </summary>
        internal static string ChanDelEmbFieldTitle {
            get {
                return ResourceManager.GetString("ChanDelEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название: **{0}**\nNSFW **{2}**\nКатегория: {3}.
        /// </summary>
        internal static string ChanEmbFieldDesc {
            get {
                return ResourceManager.GetString("ChanEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты сможешь использовать эту команду через {0} сек..
        /// </summary>
        internal static string CooldownMessage {
            get {
                return ResourceManager.GetString("CooldownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем: {0}.
        /// </summary>
        internal static string DiEvnEmbFooter {
            get {
                return ResourceManager.GetString("DiEvnEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение будет автоматически удалено через одну минуту..
        /// </summary>
        internal static string EmbFooterAboutDel {
            get {
                return ResourceManager.GetString("EmbFooterAboutDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если нашли какие либо неточности, сообщите моему создателю: Cyber_Garret#5898.
        /// </summary>
        internal static string EmbFooterAboutMyMistake {
            get {
                return ResourceManager.GetString("EmbFooterAboutMyMistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлена.
        /// </summary>
        internal static string GuMemAddRole {
            get {
                return ResourceManager.GetString("GuMemAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убрана.
        /// </summary>
        internal static string GuMemRemRole {
            get {
                return ResourceManager.GetString("GuMemRemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя: **{0}**\n{1} роль: **{2}**.
        /// </summary>
        internal static string GuMemRolEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔑 Обновлена роль стража:.
        /// </summary>
        internal static string GuMemRolEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemRolEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущее имя:\n**{0}**\nНовое имя:\n**{1}**.
        /// </summary>
        internal static string GuMemUpdEmbFieldDesc {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 Имя стража изменено:.
        /// </summary>
        internal static string GuMemUpdEmbFieldTitle {
            get {
                return ResourceManager.GetString("GuMemUpdEmbFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Заметка от лидера:** {0}.
        /// </summary>
        internal static string MilEmbDesc {
            get {
                return ResourceManager.GetString("MilEmbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Лидер боевой группы: **#1 {0} - {1}**\n- Чтобы за вами закрепилось место нажмите на реакцию {2}.
        /// </summary>
        internal static string MilEmbInfDescField {
            get {
                return ResourceManager.GetString("MilEmbInfDescField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        internal static string MilEmbInfTitleField {
            get {
                return ResourceManager.GetString("MilEmbInfTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В боевую группу записались.
        /// </summary>
        internal static string MilEmbMemTitleField {
            get {
                return ResourceManager.GetString("MilEmbMemTitleField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, в {1} по {2}. {3}: {4}.
        /// </summary>
        internal static string MilEmbTitle {
            get {
                return ResourceManager.GetString("MilEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные активности {0}..
        /// </summary>
        internal static string MilInfEmbTitle {
            get {
                return ResourceManager.GetString("MilInfEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}. Сервер: {2}.
        /// </summary>
        internal static string MilRemEmbFooter {
            get {
                return ResourceManager.GetString("MilRemEmbFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочу вам напомнить, что у вас через 15 минут начнется **{0}**..
        /// </summary>
        internal static string MilRemEmbTitle {
            get {
                return ResourceManager.GetString("MilRemEmbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестно.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://neira.su/.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
